
name: PHPUnit Full Test Suite
on:
  push:
    branches-ignore:
      - 4.x
  # Allows us to manually trigger this workflow.
  # This is great if there is a change made to Tripal core that we want to test our modules on ASAP.
  workflow_dispatch:
  # Allows us to schedule when this workflow is run.
  # This ensures we pick up any new changes committed to Tripal Core.
  schedule:
    # Run at 2am every night.
    - cron: '0 2 * * *'

env:
  PKG_NAME: TripalCultivate-Phenotypes
  MODULES: "trpcultivate_phenotypes"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
        pgsql-version:
          - "13"
          - "16"
        drupal-version:
          - "10.2.x-dev"
          - "10.3.x-dev"
          - "10.4.x-dev"

    steps:
      # Check out the repo
      - name: Checkout Repository
        uses: actions/checkout@v4
      # Here we pull the development tripaldocker image for this combo in our matrix
      - name: Run Automated testing
        uses: tripal/test-tripal-action@v1.6
        with:
          directory-name: $PKG_NAME
          modules: $MODULES
          build-image: TRUE
          dockerfile: 'Dockerfile'
          php-version: ${{ matrix.php-version }}
          pgsql-version: ${{ matrix.pgsql-version }}
          drupal-version: ${{ matrix.drupal-version }}
